### PR TITLE
support for ida7.5 ida7.6

### PR DESCRIPTION
**Pull request by sh4m2hwz**

### CODE REVIEW

**Comment by tmr232** [comment]
Thanks!
Seems like we're going to have to release a 7.5 version, as I doubt this works for 7.4, right? (I'm currently without a 7.5/7.6 license)

**Comment by sh4m2hwz** [comment]
Yes it is works on ida 7.5 and ida 7.6

**Comment by tmr232** [comment]
Sorry for the delay, I'll try to get to it soon.

**Comment by tmr232** [comment]
It seems that PyQt5 is working with 7.7?

I'll check with Hex Rays support

**Comment by tmr232** [comment]
Closing due to no repro. Please reopen with repro if needed.

**Pull request closed without merging**
