### PR TITLE
Plugin for using the IDA IPython plugin.

### PR DESCRIPTION
**Pull request by OfficialMan**
This plugin eases the usage of the IDA IPython plugin, by creating a UI menu on IDA's main menu.
Currently, the menu allows to start a linked IPython console / or a linked Qt console.

__(Of course,)__ This plugin requires the IDA IPython plugin to be installed.

### CODE REVIEW

**Comment by tmr232** [comment]
Why not add it to the IDA IPython plugin itself?

**Comment by OfficialMan** [comment]
Well, it's possible to modify the [IDA IPython plugin](https://github.com/james91b/ida_ipython), but it requires to fork its repository.
I think both options are good. Do you think it's a better option?

**Comment by tmr232** [comment]
Seems to make more sense to have 1 plugin instead of 2. Especially when one is dependent on the other.

**Comment by tmr232** [comment]
This already exists in IDA IPython. So I am closing this pull request.

**Pull request closed without merging**
